name: Reusable workflow example

on:
  workflow_call:
    inputs:
      DEPENDENCY_CHECK_SCAN_ROOT_PATH:
        required: true
      DEPENDENCY_CHECK_REPORT_PATH:
        required: false
        default: 'dependency-check-generic.json'
      DEPENDENCY_CHECK_SCAN_ADDITIONAL_FLAGS:
        required: false
        default: ''

jobs:
  dependency-check:
    runs-on: owasp/dependency-check
    steps: 
      - run: /usr/share/dependency-check/bin/dependency-check.sh --scan ${{ DEPENDENCY_CHECK_SCAN_ROOT_PATH }} --format JSON --out ${{ DEPENDENCY_CHECK_REPORT_PATH }} --enableExperimental ${{ DEPENDENCY_CHECK_SCAN_ADDITIONAL_FLAGS }} || exit 0
  sast-eslint-check:
    runs-on: registry.gitlab.com/gitlab-org/security-products/analyzers/eslint:2
    steps:
      - run: /analyzer run
  sast-nodejs-scan:
    runs-on: registry.gitlab.com/gitlab-org/security-products/analyzers/nodejs-scan:2
    steps:
      - run: /analyzer run
  sast-semgrep:
    runs-on: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2
    steps:
      - run: /analyzer run