name: Publish

on:
  workflow_call:
    inputs:
      bump_type: 
        type: string
        default: minor
        required: false
    secrets:
      NPM_DEPLOY_TOKEN:
        required: true
      PAT_GITHUB:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure CI Git User
        run: |
          git config --global user.name 'everton.tavares'
          git config --global user.email 'ezidiu@gmail.com'
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}

      - name: Install Packages
        run: yarn install

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@batatinha-delivery:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}

      - name: Publish package
        run: |
          lerna publish ${{ inputs.bump_type }} --yes --message "chore: Release new version" --conventional-commits --no-push
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
