name: Publish

on:
  workflow_call:
    inputs:
      bump_type: 
        type: string
        default: minor
        required: false
      GITHUB_REPOSITORY:
        type: string
        required: true
    secrets:
      NPM_DEPLOY_TOKEN:
        required: true
      PAT_GITHUB:
        required: true
      GH_PAGES_DEPLOY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Configure CI Git User
        run: |
          echo "Configuring ${{ github.repository }}"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT_GITHUB}@github.com/${{ github.repository }}
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
          GITHUB_REPOSITORY: ${{inputs.GITHUB_REPOSITORY}}

      - name: Install Packages
        run: yarn install

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@batatinha-delivery:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
      - name: Publish package
        run: |
          lerna version ${{ inputs.bump_type }} --yes --conventional-commits --create-release github --message "chore(release): Release new version" --no-push
          lerna publish from-package --yes
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          NODE_AUTH_TOKEN: ${{ secrets.PAT_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
      - name: Push
        run: | 
          git push --force --follow-tags --no-verify origin main
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          NODE_AUTH_TOKEN: ${{ secrets.PAT_GITHUB }}
