name: Publish

on:
  workflow_call:
    inputs:
      NPM_DEPLOY_TOKEN:
        required: true
        type: string
      PAT_GITHUB:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure CI Git User
        run: |
          git config --global user.name 'gh-actions'
          git config --global user.email 'actions@github.com'
        env:
          PAT_GITHUB: ${{ inputs.PAT_GITHUB }}

      - name: Install Packages
        run: yarn install

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@batatinha-delivery:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ inputs.NPM_DEPLOY_TOKEN }}

      - name: Publish package
        run: |
          lerna publish --yes --message "chore: Release new version"
        env:
          GH_TOKEN: ${{ inputs.PAT_GITHUB }}
          GITHUB_TOKEN: ${{ inputs.PAT_GITHUB }}
          NPM_TOKEN: ${{ inputs.NPM_DEPLOY_TOKEN }}
